import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Palette extracted 1:1 from Stitch designs (Obsidian Prism)
        primary: "#f2fff1",
        "on-primary": "#00391d",
        "primary-container": "#00ff94",
        "on-primary-container": "#00713f",
        "primary-fixed": "#5bffa1",
        "primary-fixed-dim": "#00e383",
        "on-primary-fixed": "#00210e",
        "on-primary-fixed-variant": "#00522c",
        "inverse-primary": "#006d3c",

        secondary: "#d0bcff",
        "on-secondary": "#3c0091",
        "secondary-container": "#571bc1",
        "on-secondary-container": "#c4abff",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#5516be",

        tertiary: "#fffbf9",
        "on-tertiary": "#3c2f00",
        "tertiary-container": "#ffdc71",
        "on-tertiary-container": "#775f00",
        "tertiary-fixed": "#ffe085",
        "tertiary-fixed-dim": "#e5c45b",
        "on-tertiary-fixed": "#231b00",
        "on-tertiary-fixed-variant": "#574500",

        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",

        background: "#131313",
        "on-background": "#e5e2e1",
        surface: "#131313",
        "surface-dim": "#131313",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#b9cbbb",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "surface-tint": "#00e383",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#849586",
        "outline-variant": "#3b4b3e",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "jetbrains-mono": ["'JetBrains Mono'", "ui-monospace", "monospace"],
        "data-mono": ["'JetBrains Mono'", "ui-monospace", "monospace"],
        "headline-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "system-ui", "sans-serif"],
        "display-lg": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        "label-sm": ["'JetBrains Mono'", "ui-monospace", "monospace"],
        "label-caps": ["'JetBrains Mono'", "ui-monospace", "monospace"],
        "code-md": ["'JetBrains Mono'", "ui-monospace", "monospace"],
        "stats-lg": ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "700" }],
        "code-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "stats-lg": ["20px", { lineHeight: "1", letterSpacing: "-0.03em", fontWeight: "500" }],
        "data-mono": ["14px", { lineHeight: "1.5", letterSpacing: "0.01em", fontWeight: "500" }],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        gutter: "24px",
        margin: "32px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
