import {
  Activity,
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  Bot,
  Boxes,
  CheckCircle2,
  ChevronRight,
  Code2,
  Copy,
  CreditCard,
  Eye,
  EyeOff,
  Files,
  Globe,
  Hexagon,
  Home,
  Key,
  Layers,
  LineChart,
  Loader2,
  Lock,
  LogOut,
  type LucideIcon,
  Network,
  Plus,
  Receipt,
  RefreshCw,
  Route,
  Search,
  Settings,
  Shield,
  Sparkles,
  Terminal,
  TrendingDown,
  TrendingUp,
  Users,
  Wallet,
  Wand2,
  Zap,
} from "lucide-react";

export const Icons = {
  activity: Activity,
  alert: AlertTriangle,
  arrow: ArrowRight,
  upRight: ArrowUpRight,
  bot: Bot,
  boxes: Boxes,
  check: CheckCircle2,
  chevron: ChevronRight,
  code: Code2,
  copy: Copy,
  card: CreditCard,
  eye: Eye,
  eyeOff: EyeOff,
  files: Files,
  globe: Globe,
  hex: Hexagon,
  home: Home,
  key: Key,
  layers: Layers,
  line: LineChart,
  spinner: Loader2,
  lock: Lock,
  logOut: LogOut,
  network: Network,
  plus: Plus,
  receipt: Receipt,
  refresh: RefreshCw,
  route: Route,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  terminal: Terminal,
  trendDown: TrendingDown,
  trendUp: TrendingUp,
  users: Users,
  wallet: Wallet,
  wand: Wand2,
  zap: Zap,
};

export type IconKey = keyof typeof Icons;

export function Icon({ name, className }: { name: IconKey; className?: string }) {
  const Component: LucideIcon = Icons[name];
  return <Component className={className} />;
}
